<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0f5AG8b\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0f5AG8b/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0f5AG8b.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0f5AG8b\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0f5AG8b\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0f5AG8b',
    'container.build_id' => '4c994452',
    'container.build_time' => 1518365824,
));
